[tool.poetry]
name = "agent-controller"
version = "0.1.0"
description = "Controller backend"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

